###_____________run tomcat 9.0 image via docker hub____________________
FROM tomcat:9.0-slim

COPY ./editor/swagger-editor.war /usr/local/tomcat/webapps/
COPY ./src/main/swagger/openapi.yaml /home/editor.yaml

ENV JAVA_OPTS "-DswaggerUrl=/home/editor.yaml"

CMD ["catalina.sh", "run"]

##--- A fix made to run swagger-editor.war under tomcat:9.0-slim image
##--- Inside of the war, remove default content path of '/v1/specs'. 
##--- It should look like this in 'index.html'
##---   const editor = SwaggerEditorBundle({
##---       dom_id: '#swagger-editor',
##---       layout: 'StandaloneLayout',
##---       presets: [
##---         SwaggerEditorStandalonePreset
##---       ]

##--- 1. Running docker local
##--- % docker build -t inflector-tomcat-image -f Dockerfile-image .
##--- % docker run -d -p 8080:8080 inflector-tomcat-image

##--- 2. Running an image after push/pull via docker hub
##--- 2.a. label an image 
##--- % docker image ls
##---       REPOSITORY                                TAG        IMAGE ID       CREATED        SIZE
##---       inflector-tomcat-image                    latest     5809f6636b61   21 hours ago   441MB
##--- % docker tag 5809f6636b61 tony4docker2msn/inflector-tomcat-image:latest   
##--- % docker image ls                                                       
##---       REPOSITORY                                TAG        IMAGE ID       CREATED        SIZE
##---       inflector-tomcat-image                    latest     5809f6636b61   21 hours ago   441MB
##---       tony4docker2msn/inflector-tomcat-image    latest     5809f6636b61   21 hours ago   441MB
##--- 2.b  push/pull an image via docker hub and run it afterward
##--- % docker push tony4docker2msn/inflector-tomcat-image:latest
##--- % docker pull tony4docker2msn/inflector-tomcat-image:latest   
##--- % docker run -d -p 8080:8080 tony4docker2msn/inflector-tomcat-image:latest
##--- 3. Hit the tomcat server
##--- visit 'http://localhost:8080/swagger-editor/'
##--- ATTN: it is not 'http://localhost:8080/'
##--- A context path of 'swagger-edit/' required after docker 'COPY' the war file 
